added a verification step

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -102,23 +102,7 @@ jobs:
         cmake -DCMAKE_BUILD_TYPE=Release -A $BUILD_ARCH ..\\Libraries
 
         cmake --build . --config Release -j 2
-
-        cd $GITHUB_WORKSPACE\\build
-
-    # add a verification step
-    - name:  Sign Build
-      env: 
-        CODESIGN_BASE64: ${{ secrets.WINDOWS_CERTIFICATE}}
-      if: runner.os == 'Windows'
-      shell: pwsh
-      run:   |
-        New-Item -ItemType directory -Path certificate
-        Set-Content -Path certificate\certificate.txt -Value $env:CODESIGN_BASE64
-        certutil -decode certificate\certificate.txt certificate\certificate.pfx
-        $signtool = "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"
-        & $signtool sign /fd sha256 /f certificate\certificate.pfx $env:GITHUB_WORKSPACE\build\vsp\Release\vsp.exe
-        Remove-Item -Recurse -Force certificate
-
+  
     - name: Deploy Windows 
       if: runner.os == 'Windows'
       shell: bash
@@ -138,7 +122,22 @@ jobs:
         cp $ZIPFILE $DEPLOY_FILE
         cp $DEPLOY_FILE $GITHUB_WORKSPACE\\artifacts
 
-        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1) 
+        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
+
+    # add a verification step
+    - name:  Sign Build
+      env: 
+        CODESIGN_BASE64: ${{ secrets.WINDOWS_CERTIFICATE}}
+      if: runner.os == 'Windows'
+      shell: pwsh
+      run:   |
+        New-Item -ItemType directory -Path certificate
+        Set-Content -Path certificate\certificate.txt -Value $env:CODESIGN_BASE64
+        certutil -decode certificate\certificate.txt certificate\certificate.pfx
+        $signtool = "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"
+        & $signtool sign /fd sha256 /f certificate\certificate.pfx $env:GITHUB_WORKSPACE\build\vsp\Release\vsp.exe
+        & $signtool verify /pa $env:GITHUB_WORKSPACE\build\vsp\Release\vsp.exe
+        Remove-Item -Recurse -Force certificate
 
     # - name:  Build MacOS
     #   if: runner.os == 'macos'
