split the build and package step

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -103,7 +103,7 @@ jobs:
 
         cmake --build . --config Release -j 2
   
-    - name: Build Windows 
+    - name:  Build Windows 
       if: runner.os == 'Windows'
       shell: bash
       run:   |
@@ -143,6 +143,21 @@ jobs:
 
         Remove-Item -Recurse -Force certificate
 
+    - name:  Package Windows
+      if: runner.os == 'Windows'
+      shell: bash
+      run:   |
+        make package
+        ZIPFILE=OpenVSP*.zip
+        VSPVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
+        WINVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $3 }' | awk 'BEGIN { FS = "." } ; { print $1 }' )
+        
+        DEPLOY_FILE=OpenVSP-${VSPVER}-${WINVER}-Python${{ matrix.python-version }}_${GITHUB_SHA}.zip
+        cp $ZIPFILE $DEPLOY_FILE
+        cp $DEPLOY_FILE $GITHUB_WORKSPACE\\artifacts
+
+        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
+        
     # - name:  Build MacOS
     #   if: runner.os == 'macos'
     #   shell: bash
