Modified build/yml file for testing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,7 +2,8 @@ name: CMake Build Matrix
 
 on:
   push:
-    branches: build
+    # branches: build
+    branches: TestBuild
 
 jobs:
   build:
@@ -13,7 +14,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: [3.6, 3.9] # specify more python versions here (i.e. 3.9)
+        # python-version: [3.6, 3.9] # specify more python versions here (i.e. 3.9)
+        python-version: [3.9] # specify more python versions here (i.e. 3.9)
         config:
         - {
             name: "Windows 64",
@@ -21,24 +23,24 @@ jobs:
             arch: x64,
             python-arch: x64,
           }
-        - {
-            name: "Ubuntu 20.04",
-            os: ubuntu-20.04,
-            arch: x64,
-            python-arch: x64,
-          }
-        - {
-            name: "Ubuntu 22.04",
-            os: ubuntu-22.04,
-            arch: x64,
-            python-arch: x64,
-          }
-        - {
-            name: "macOS 11",
-            os: macos-11,
-            arch: x64,
-            python-arch: x64,
-          }
+        # - {
+        #     name: "Ubuntu 20.04",
+        #     os: ubuntu-20.04,
+        #     arch: x64,
+        #     python-arch: x64,
+        #   }
+        # - {
+        #     name: "Ubuntu 22.04",
+        #     os: ubuntu-22.04,
+        #     arch: x64,
+        #     python-arch: x64,
+        #   }
+        # - {
+        #     name: "macOS 11",
+        #     os: macos-11,
+        #     arch: x64,
+        #     python-arch: x64,
+        #   }
 
     steps:
     - name: Checkout
@@ -51,45 +53,45 @@ jobs:
         python-version: ${{ matrix.python-version }}
         architecture: ${{ matrix.config.python-arch }}
 
-    - name:  Install Linux
-      if: runner.os == 'Linux'
-      shell: bash
-      run:   |
-        sudo apt-get update
-        sudo apt-get install python3-dev libxml2-dev libfltk1.3-dev fluid libjpeg-dev libglm-dev libcminpack-dev libglew-dev swig doxygen graphviz texlive-latex-base zip
+    # - name:  Install Linux
+    #   if: runner.os == 'Linux'
+    #   shell: bash
+    #   run:   |
+    #     sudo apt-get update
+    #     sudo apt-get install python3-dev libxml2-dev libfltk1.3-dev fluid libjpeg-dev libglm-dev libcminpack-dev libglew-dev swig doxygen graphviz texlive-latex-base zip
 
     - name:  Install Windows
       if: runner.os == 'Windows'
       shell: cmd
       run:   choco install -y swig
 
-    - name:  Install MacOS
-      if: runner.os == 'macos'
-      shell: bash
-      run:   brew install swig gcc@10
+    # - name:  Install MacOS
+    #   if: runner.os == 'macos'
+    #   shell: bash
+    #   run:   brew install swig gcc@10
 
-    - name:  Build Linux
-      if: runner.os == 'Linux'
-      shell: bash
-      run:   |
-        mkdir build buildlibs artifacts
-        cd $GITHUB_WORKSPACE/buildlibs
-        cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DVSP_USE_SYSTEM_CPPTEST=false ../Libraries
-        make -j2
+    # - name:  Build Linux
+    #   if: runner.os == 'Linux'
+    #   shell: bash
+    #   run:   |
+    #     mkdir build buildlibs artifacts
+    #     cd $GITHUB_WORKSPACE/buildlibs
+    #     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DVSP_USE_SYSTEM_CPPTEST=false ../Libraries
+    #     make -j2
         
-        cd $GITHUB_WORKSPACE/build
-        cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs ../src
-        make -j2 package
+    #     cd $GITHUB_WORKSPACE/build
+    #     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs ../src
+    #     make -j2 package
         
-        DEBFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-Linux.deb
-        VSPVER=$(ls $DEBFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
-        UVER=$(lsb_release -sr)
-        DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-Ubuntu-${UVER}_amd64_${GITHUB_SHA}.deb
+    #     DEBFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-Linux.deb
+    #     VSPVER=$(ls $DEBFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
+    #     UVER=$(lsb_release -sr)
+    #     DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-Ubuntu-${UVER}_amd64_${GITHUB_SHA}.deb
         
-        cp $DEBFILE $DEPLOY_FILE
-        cp $DEPLOY_FILE $GITHUB_WORKSPACE/artifacts
+    #     cp $DEBFILE $DEPLOY_FILE
+    #     cp $DEPLOY_FILE $GITHUB_WORKSPACE/artifacts
         
-        ls $DEPLOY_FILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1)
+    #     ls $DEPLOY_FILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1)
 
     - name:  Build Windows
       if: runner.os == 'Windows'
@@ -116,27 +118,27 @@ jobs:
         
         ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
 
-    - name:  Build MacOS
-      if: runner.os == 'macos'
-      shell: bash
-      run:   |
-        mkdir build buildlibs artifacts
-        cd $GITHUB_WORKSPACE/buildlibs
-        cmake -DCMAKE_BUILD_TYPE=Release ../Libraries -DADEPT_CXX_COMPILER=/usr/local/bin/g++-10 -DADEPT_C_COMPILER=/usr/local/bin/gcc-10
-        make -j2
+    # - name:  Build MacOS
+    #   if: runner.os == 'macos'
+    #   shell: bash
+    #   run:   |
+    #     mkdir build buildlibs artifacts
+    #     cd $GITHUB_WORKSPACE/buildlibs
+    #     cmake -DCMAKE_BUILD_TYPE=Release ../Libraries -DADEPT_CXX_COMPILER=/usr/local/bin/g++-10 -DADEPT_C_COMPILER=/usr/local/bin/gcc-10
+    #     make -j2
         
-        cd $GITHUB_WORKSPACE/build
-        cmake -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs -DCXX_OMP_COMPILER=/usr/local/bin/g++-10 -DC_OMP_COMPILER=/usr/local/bin/gcc-10 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" ../src;
-        make -j2 package
+    #     cd $GITHUB_WORKSPACE/build
+    #     cmake -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs -DCXX_OMP_COMPILER=/usr/local/bin/g++-10 -DC_OMP_COMPILER=/usr/local/bin/gcc-10 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" ../src;
+    #     make -j2 package
         
-        ZIPFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-MacOS.zip
-        VSPVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
-        DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-MacOS-Python${{ matrix.python-version }}_${GITHUB_SHA}.zip
+    #     ZIPFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-MacOS.zip
+    #     VSPVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
+    #     DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-MacOS-Python${{ matrix.python-version }}_${GITHUB_SHA}.zip
         
-        cp $ZIPFILE $DEPLOY_FILE
-        cp $DEPLOY_FILE $GITHUB_WORKSPACE/artifacts
+    #     cp $ZIPFILE $DEPLOY_FILE
+    #     cp $DEPLOY_FILE $GITHUB_WORKSPACE/artifacts
         
-        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
+    #     ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
 
     - name: Generate Documentation
       if: matrix.config.os == 'ubuntu-20.04'
